### PR TITLE
32 - using wget instead of curl for jdk alpine docker image health checks

### LINKED ISSUE #32: Multiple containers failing health checks
Healthchecks on a fresh `docker compose up -d` run are failing on the message listener, REST, and processor containers. This is down to multiple factors.

1. Some software is not fully launching due to #31.
2. `curl` is not installed in the image the containers are built from, and as such, even if the software launched flawlessly, the healtcheck would fail.

I'd suggest adding curl with a `RUN apk add curl` step in the relevant Dockerfiles. 

cc @pveeckhout 
Related #27 #28 #31

### PR DESCRIPTION
**Pull request by pveeckhout**

### CODE REVIEW

**Comment by TheGuyDanish** [comment]
Still seeing `Up 2 minutes (unhealthy)` on the message listener, though looking into the container it's not looking like the java process is listening on any port.

```
/home/backend # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:36921        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:52884        0.0.0.0:*                           -
/home/backend # ps aux
PID   USER     TIME  COMMAND
    1 backend   0:41 java -jar app.jar
  191 root      0:00 sh
  204 root      0:00 ps aux
```

Does it not listen on any port or has it not started properly in this instance?

**Comment by pveeckhout** [comment]
I just saw it to. This wil be for when I actually get home. I had hoped a quick wget swap would've fixed it

**Comment by TheGuyDanish** [comment]
All good man, take your time and enjoy your time away. 👍

**Comment by pveeckhout** [comment]
I just noticed this depends on changes made in #31 ... still after merging those in message-listener still shows as unhealthy eventhough it is up and running

**Pull request closed without merging**
